### ISSUE TITLE
Type checking errors can fail for primitive types 

### ISSUE THREAD

**Issue by thermokarst** [qiime2/qiime2#437]
**Bug Description**
The type mismatch exception message uses QIIME 2 API specific to Artifacts (`kwarg.type`), which breaks down when `kwarg` is a primitive type (like `float`).

This bug was introduced in #417.

**Steps to reproduce the behavior**
```python
import qiime2
from qiime2.plugins import metadata
md = qiime2.Metadata.load('some_md.tsv')
metadata.actions.tabulate(input=md, page_size=0.5). # page_size should be an int...
```

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-46d72e1c9e55> in <module>
----> 1 metadata.actions.tabulate(input=md, page_size=0.5)

<decorator-gen-338> in tabulate(input, page_size)

~/src/qiime2/qiime2/qiime2/sdk/action.py in bound_callable(*args, **kwargs)
    197
    198                 # Type management
--> 199                 self.signature.check_types(**user_input)
    200                 output_types = self.signature.solve_output(**user_input)
    201                 callable_args = {}

~/src/qiime2/qiime2/qiime2/core/type/signature.py in check_types(self, **kwargs)
    299                         "Parameter %r received an argument of type %r. An "
    300                         "argument of subtype %r is required." % (
--> 301                             name, kwargs[name].type, spec.qiime_type))
    302
    303     def solve_output(self, **input_types):

AttributeError: 'float' object has no attribute 'type'
```

**Expected behavior**
The exception should work for primitive types, too.

**References**
1. [Original forum post](https://forum.qiime2.org/t/error-float-object-has-no-attribute-type-in-otu-clustering/8087)
